In [1]:
#Ques-1 Arrays using numpy
import numpy
def arrays(arr):
    c = numpy.array(arr[::-1],float)
    return c
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 5 -8 -9
[-9. -8.  5.  4.  3.  2.  1.]


In [2]:
#Ques-2 Shape and reshape
import numpy as np
a = input().split()
b = np.array(a,int)
c = b.reshape(3,3)
print(c)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
#Ques-3 Transpose and flatten
import numpy
a,b = map(int,input().split())
c = numpy.array([input().split() for i in range(a)],int)
print(c.transpose())
print(c.flatten())

2 2
2 3
5 6
[[2 5]
 [3 6]]
[2 3 5 6]


In [12]:
#Ques-4 Zeros and ones
import numpy as np
a = list(map(int,input().split()))
print(np.zeros(a,dtype=np.int))
print(np.ones(a,dtype=np.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [13]:
#Ques-5 Concatenate
import numpy as np
a,b,c = map(int,input().split())
d = np.array([input().split() for i in range(a)],int)
e = np.array([input().split() for i in range(b)],int)
print(np.concatenate((d,e),axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [17]:
#Ques-6 Eye and Identity
import numpy as np
n,m=map(int,input().split())
np.set_printoptions(legacy='1.13')
print(np.eye(n,m))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [18]:
#Ques-7 Array Mathematics
import numpy as np
a,b = map(int,input().split())
c = np.array([input().split() for i in range(a)],int)
d = np.array([input().split() for i in range(a)],int)
print(np.add(c,d))
print(np.subtract(c,d))
print(np.multiply(c,d))
print(np.floor_divide(c,d))
print(np.mod(c,d))
print(np.power(c,d))

1 4 
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [19]:
#Ques-8 Floor,Ceil and Rint
import numpy as np
n = input().split()
a = np.array(n,float)
np.set_printoptions(legacy='1.13')
print(np.floor(a))
print(np.ceil(a))
print(np.rint(a))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [20]:
#Ques-9 Sum and Product
import numpy as np
a,b = map(int,input().split())
my_arr = np.array([input().split() for i in range(a)],int)
d = np.sum(my_arr,axis=0)
print(np.prod(d))

2 2 
1 2 
3 4
24


In [22]:
#Ques-10 Minimum and Maximum
import numpy as np
a,d = map(int,input().split())
b = np.array([input().split() for i in range(a)],int)
c = np.min(b,axis=1)
print(np.max(c))

4 3
2 5 
8 6
9 3
1 7
6


In [23]:
#Ques-11 Mean,Variance and Standard variance
import numpy as np
a,b = map(int,input().split())
c = np.array([input().split() for i in range(a)],int)
print(np.mean(c,axis=1))
print(np.var(c,axis=0))
print(np.std(c,axis=None))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [25]:
#Ques-12 Dot and Cross
import numpy as np
a = int(input())
b = np.array([input().split() for i in range(a)],int)
c = np.array([input().split() for i in range(a)],int)
print(np.dot(b,c))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [26]:
#Ques-13 Inner and Outer
import numpy as np
a = list(map(int,input().split()))
b = list(map(int,input().split()))
print(np.inner(a,b))
print(np.outer(a,b))

0 1
3 5
5
[[0 0]
 [3 5]]


In [27]:
#Ques-14 Polynomials
import numpy as np
a = list(map(float,input().split()))
b = int(input())
print(np.polyval(a,b))

1.1 2 3
0
3.0


In [28]:
#Ques-15 Linear algebra
import numpy as np
a = int(input())
b = np.array([input().split() for i in range(a)],float)
print(np.linalg.det(b))

2
1.1 1.1
1.1 1.1
0.0
